### ISSUE TITLE
Clean up codebase

### ISSUE THREAD

**Issue by gowrizrh** [aligent/magento-async-events#6]
The module contains some inconsistent code styles across the codebase. Examples include use of fully qualified namespace declarations, `_property` vs `property` and just general code style.

This needs to be refactored and probably is a good first issue to anyone looking to explore the codebase more.

**Comment by gowrizrh** [comment]
### Some pointers

- [x] Remove all unnecessary fully qualified namespace declarations **UNLESS** it is used to define DTOs and Services. i.e: any interface that is defined in an `webpi.xml` or `async_events.xml` or under `Api/`
- [x] `AsyncEventLog` needs to have type hinting in method params and returns. Setters should not return `$this`
- [x] `NotifierResult` needs to be extending `\Magento\Framework\DataObject` to set and get property values.
- [x] Remove Aligent Copyright comment in files. example: `Controller/Adminhtml/Logs/Index.php`

**Comment by anthony-dinino-aligent** [comment]
@gowrizrh I made a PR for the `NotifierResult` [here](https://github.com/aligent/magento-async-events/pull/24)
